import { User, Role, Permission } from "./types";

// Mock data for users
export const mockUsers: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john",
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-06-20T14:45:00Z",
    roles: [
      {
        id: "1",
        name: "Admin",
        description: "Full system access",
        permissions: [],
        createdAt: "",
        updatedAt: "",
      },
    ],
    status: "active",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jane",
    createdAt: "2023-02-10T09:15:00Z",
    updatedAt: "2023-05-18T11:20:00Z",
    roles: [
      {
        id: "2",
        name: "Editor",
        description: "Can edit content",
        permissions: [],
        createdAt: "",
        updatedAt: "",
      },
    ],
    status: "active",
  },
  {
    id: "3",
    name: "Robert Johnson",
    email: "robert@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=robert",
    createdAt: "2023-03-05T16:45:00Z",
    updatedAt: "2023-03-05T16:45:00Z",
    roles: [
      {
        id: "3",
        name: "Viewer",
        description: "Read-only access",
        permissions: [],
        createdAt: "",
        updatedAt: "",
      },
    ],
    status: "inactive",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emily",
    createdAt: "2023-04-20T13:10:00Z",
    updatedAt: "2023-07-12T09:30:00Z",
    roles: [
      {
        id: "2",
        name: "Editor",
        description: "Can edit content",
        permissions: [],
        createdAt: "",
        updatedAt: "",
      },
    ],
    status: "active",
  },
  {
    id: "5",
    name: "Michael Wilson",
    email: "michael@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=michael",
    createdAt: "2023-05-15T11:25:00Z",
    updatedAt: "2023-05-15T11:25:00Z",
    roles: [
      {
        id: "3",
        name: "Viewer",
        description: "Read-only access",
        permissions: [],
        createdAt: "",
        updatedAt: "",
      },
    ],
    status: "pending",
  },
];

// Mock data for roles
export const mockRoles: Role[] = [
  {
    id: "1",
    name: "Admin",
    description: "Full system access",
    permissions: [
      {
        id: "1",
        name: "users.create",
        description: "Create users",
        category: "Users",
        createdAt: "",
        updatedAt: "",
      },
      {
        id: "2",
        name: "users.read",
        description: "View users",
        category: "Users",
        createdAt: "",
        updatedAt: "",
      },
      {
        id: "3",
        name: "users.update",
        description: "Update users",
        category: "Users",
        createdAt: "",
        updatedAt: "",
      },
      {
        id: "4",
        name: "users.delete",
        description: "Delete users",
        category: "Users",
        createdAt: "",
        updatedAt: "",
      },
      {
        id: "5",
        name: "roles.manage",
        description: "Manage roles",
        category: "Roles",
        createdAt: "",
        updatedAt: "",
      },
      {
        id: "6",
        name: "permissions.manage",
        description: "Manage permissions",
        category: "Permissions",
        createdAt: "",
        updatedAt: "",
      },
    ],
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Editor",
    description: "Can edit content",
    permissions: [
      {
        id: "2",
        name: "users.read",
        description: "View users",
        category: "Users",
        createdAt: "",
        updatedAt: "",
      },
      {
        id: "7",
        name: "content.create",
        description: "Create content",
        category: "Content",
        createdAt: "",
        updatedAt: "",
      },
      {
        id: "8",
        name: "content.update",
        description: "Update content",
        category: "Content",
        createdAt: "",
        updatedAt: "",
      },
    ],
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Viewer",
    description: "Read-only access",
    permissions: [
      {
        id: "2",
        name: "users.read",
        description: "View users",
        category: "Users",
        createdAt: "",
        updatedAt: "",
      },
      {
        id: "9",
        name: "content.read",
        description: "View content",
        category: "Content",
        createdAt: "",
        updatedAt: "",
      },
    ],
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
];

// Mock data for permissions
export const mockPermissions: Permission[] = [
  {
    id: "1",
    name: "users.create",
    description: "Create users",
    category: "Users",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "users.read",
    description: "View users",
    category: "Users",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "users.update",
    description: "Update users",
    category: "Users",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "4",
    name: "users.delete",
    description: "Delete users",
    category: "Users",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "5",
    name: "roles.manage",
    description: "Manage roles",
    category: "Roles",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "6",
    name: "permissions.manage",
    description: "Manage permissions",
    category: "Permissions",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "7",
    name: "content.create",
    description: "Create content",
    category: "Content",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "8",
    name: "content.update",
    description: "Update content",
    category: "Content",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "9",
    name: "content.read",
    description: "View content",
    category: "Content",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "10",
    name: "content.delete",
    description: "Delete content",
    category: "Content",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "11",
    name: "settings.manage",
    description: "Manage settings",
    category: "Settings",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "12",
    name: "analytics.view",
    description: "View analytics",
    category: "Analytics",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
];
