import { AIModel } from "./types";

export const mockAIModels: AIModel[] = [
  {
    id: "1",
    name: "GPT-4",
    provider: "OpenAI",
    version: "1.0",
    description: "Advanced language model with strong reasoning capabilities",
    capabilities: ["text-generation", "chat-completion", "function-calling"],
    parameters: {
      temperature: 0.7,
      topP: 1,
      frequencyPenalty: 0,
      presencePenalty: 0,
    },
    contextLength: 8192,
    status: "active",
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2023-06-20T14:45:00Z",
    prompts: [
      {
        id: "p1",
        name: "Customer Support Greeting",
        description: "Initial greeting for customer support interactions",
        content:
          "You are a helpful customer support assistant for {{company_name}}. Be friendly, concise, and helpful. The user is a customer who may need help with our products or services.",
        category: "customer-support",
      },
      {
        id: "p2",
        name: "Technical Support",
        description: "Technical troubleshooting assistance",
        content:
          "You are a technical support specialist for {{company_name}}. Help users troubleshoot issues with our software. Ask clarifying questions when needed and provide step-by-step solutions.",
        category: "technical",
      },
    ],
  },
  {
    id: "2",
    name: "Claude 2",
    provider: "Anthropic",
    version: "2.0",
    description: "Helpful, harmless, and honest AI assistant",
    capabilities: ["text-generation", "chat-completion"],
    parameters: {
      temperature: 0.5,
      topP: 0.9,
      frequencyPenalty: 0.1,
      presencePenalty: 0.1,
    },
    contextLength: 100000,
    status: "active",
    createdAt: "2023-02-10T09:15:00Z",
    updatedAt: "2023-05-18T11:20:00Z",
    prompts: [
      {
        id: "p3",
        name: "Sales Assistant",
        description: "Helps with product recommendations",
        content:
          "You are a knowledgeable sales assistant for {{company_name}}. Help customers find the right products based on their needs. Be informative but not pushy.",
        category: "sales",
      },
    ],
  },
  {
    id: "3",
    name: "GPT-3.5 Turbo",
    provider: "OpenAI",
    version: "3.5",
    description: "Fast and cost-effective language model",
    capabilities: ["text-generation", "chat-completion", "function-calling"],
    parameters: {
      temperature: 0.8,
      topP: 1,
      frequencyPenalty: 0,
      presencePenalty: 0,
    },
    contextLength: 4096,
    status: "active",
    createdAt: "2023-03-05T16:45:00Z",
    updatedAt: "2023-03-05T16:45:00Z",
    prompts: [],
  },
  {
    id: "4",
    name: "Gemini Pro",
    provider: "Google",
    version: "1.0",
    description: "Multimodal model with strong reasoning capabilities",
    capabilities: ["text-generation", "chat-completion", "image-generation"],
    parameters: {
      temperature: 0.7,
      topP: 0.95,
      frequencyPenalty: 0.2,
      presencePenalty: 0.2,
    },
    contextLength: 32768,
    status: "active",
    createdAt: "2023-04-20T13:10:00Z",
    updatedAt: "2023-07-12T09:30:00Z",
    prompts: [],
  },
  {
    id: "5",
    name: "GPT-3",
    provider: "OpenAI",
    version: "3.0",
    description: "Legacy language model",
    capabilities: ["text-generation"],
    parameters: {
      temperature: 0.7,
      topP: 1,
      frequencyPenalty: 0,
      presencePenalty: 0,
    },
    contextLength: 2048,
    status: "deprecated",
    createdAt: "2023-05-15T11:25:00Z",
    updatedAt: "2023-05-15T11:25:00Z",
    prompts: [],
  },
];
